# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mAtTeOpIaZzA.oRG
email: matteo.piazza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Buffo, buffissimo, meraviglioso correre.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: azzaipoettam
github_username:  arcadeJHS
facebook_username: matteo.piazza.167

permalink: pretty

# Build settings
markdown: kramdown